//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSplit.Racetime.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveSplit.Racetime.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string CREATE_RACE_ADDRESS {
            get {
                return ResourceManager.GetString("CREATE_RACE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to racetime.gg.
        /// </summary>
        internal static string DOMAIN {
            get {
                return ResourceManager.GetString("DOMAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to races/data.
        /// </summary>
        internal static string ENDPOINT_RACES {
            get {
                return ResourceManager.GetString("ENDPOINT_RACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S256.
        /// </summary>
        internal static string OAUTH_CHALLENGE_METHOD {
            get {
                return ResourceManager.GetString("OAUTH_CHALLENGE_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dKgJFc2jZjgMtUT4Ik9kyJSCZkVqRK1poCcvpKox.
        /// </summary>
        internal static string OAUTH_CLIENTID {
            get {
                return ResourceManager.GetString("OAUTH_CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rl6gGXy9zPw5xkSa0gSdE69lnlqbTwuZDAFNSDTgY5QKbQ9AqsqDYlotNGMBboDGkZFbJm9fSIpfI3sCGc3UiiZ2sEpk8KpxYf4kh0G7TjmYmgn0AXyNJNzkgIorHAcB.
        /// </summary>
        internal static string OAUTH_CLIENTSECRET {
            get {
                return ResourceManager.GetString("OAUTH_CLIENTSECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/authorize.
        /// </summary>
        internal static string OAUTH_ENDPOINT_AUTHORIZATION {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_AUTHORIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/done?error=access_denied.
        /// </summary>
        internal static string OAUTH_ENDPOINT_FAILURE {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/revoke_token.
        /// </summary>
        internal static string OAUTH_ENDPOINT_REVOKE {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_REVOKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/done.
        /// </summary>
        internal static string OAUTH_ENDPOINT_SUCCESS {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/token.
        /// </summary>
        internal static string OAUTH_ENDPOINT_TOKEN {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o/userinfo.
        /// </summary>
        internal static string OAUTH_ENDPOINT_USERINFO {
            get {
                return ResourceManager.GetString("OAUTH_ENDPOINT_USERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string OAUTH_REDIRECT_ADDRESS {
            get {
                return ResourceManager.GetString("OAUTH_REDIRECT_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4888.
        /// </summary>
        internal static string OAUTH_REDIRECT_PORT {
            get {
                return ResourceManager.GetString("OAUTH_REDIRECT_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read chat_message race_action.
        /// </summary>
        internal static string OAUTH_SCOPES {
            get {
                return ResourceManager.GetString("OAUTH_SCOPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://racetime.gg.
        /// </summary>
        internal static string OAUTH_SERVER {
            get {
                return ResourceManager.GetString("OAUTH_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https.
        /// </summary>
        internal static string PROTOCOL_REST {
            get {
                return ResourceManager.GetString("PROTOCOL_REST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wss.
        /// </summary>
        internal static string PROTOCOL_WEBSOCKET {
            get {
                return ResourceManager.GetString("PROTOCOL_WEBSOCKET", resourceCulture);
            }
        }
    }
}
