//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveSplit.Web.Share
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class ShareSettings : global::System.Configuration.ApplicationSettingsBase
    {

        private static ShareSettings defaultInstance = ((ShareSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ShareSettings())));

        public static ShareSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterFormat
        {
            get
            {
                return ((string)(this["TwitterFormat"]));
            }
            set
            {
                this["TwitterFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchFormat
        {
            get
            {
                return ((string)(this["TwitchFormat"]));
            }
            set
            {
                this["TwitchFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitterFormatRunning
        {
            get
            {
                return ((string)(this["TwitterFormatRunning"]));
            }
            set
            {
                this["TwitterFormatRunning"] = value;
            }
        }
    }
}
